'''A collection of constants in human readable form used througout the app.'''
# Push buttons
PUSHBUTTON_ADD = 0
PUSHBUTTON_EDIT = 1
PUSHBUTTON_CANCEL = 2
PUSHBUTTON_SAVE = 3
PUSHBUTTON_DELETE = 4
PUSHBUTTON_QUIT = 5

# Database Pending Action
DBPENDING_NONE = 0
DBPENDING_INSERT = 1
DBPENDING_UPDATE = 2
DBPENDING_DELETE = 3
DBPENDING_SELECT = 4  

# Enable, disabled
ENABLE = True
DISABLE = False

# App status
APP_STARTUP = 0
APP_UPLOAD = 1
APP_SAVE = 2
APP_LISTCHANGE = 3
APP_ADD = 4
APP_CANCEL = 5
APP_DELETE = 6
APP_EDIT = 7

#  SQL Statement Links
SQL_SELECT_ALL = 0
SQL_FOR_UPLOAD = 1
SQL_INSERT = 2
SQL_DELETE = 3
SQL_UPDATE = 4
SQL_UPDATE_MARKED = 5
SQL_DELETE_MARKED = 6

# Combo Load
RADIO_FREQUENCIES = 7
CENTER_DATA_FREQUENCIES = 8
MODEMS = 9
MODES = 10
RADIO_STATIONS = 11
BANDWIDTHS = 12
